name: Build, Scan, and Push to ECR (React)

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    name: Build, Scan, and Push Docker Image
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1 
      ECR_REPO_NAME: react-ms-ecr-repo 

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Checkout main branch from GitLab repo
        run: |
          git clone --branch master https://gitlab.com/cloud-devops-assignments/spring-boot-react-example gitlab-repo

      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      - name: Run Snyk scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd gitlab-repo
          snyk test --react || echo "Snyk scan completed with vulnerabilities"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag Docker image
        run: |
          cd gitlab-repo
          docker build -t ${{ secrets.ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:${{ github.run_number}} -f ../services/react/Dockerfile .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:${{ github.run_number}}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Install Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.51.3/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Set environment variables
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "ENV_PATH=./services/react/dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "qa" ]]; then
            echo "ENV_PATH=./services/react/qa" >> $GITHUB_ENV
          else
            echo "Invalid branch: ${{ github.ref_name }}"
            exit 1
          fi

      - name: Run Terragrunt init
        working-directory: ./services/react/dev 
        run: terragrunt init

      - name: Run Terragrunt plan
        working-directory: ./services/react/dev 
        run: terragrunt plan

      - name: Run Terragrunt apply
        working-directory: ./services/react/dev 
        run: terragrunt apply --auto-approve

      - name: Run Terragrunt Destroy
        working-directory: ./services/react/dev 
        run: terragrunt destroy --auto-approve
        
