name: Build, Scan, and Push to ECR

on:
  push:
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     target_branch:
  #       description: "The branch to checkout from the other repository"
  #       required: true
  #       default: "dev"

jobs:
  build-and-push:
    name: Build, Scan, and Push Docker Image
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1 # Change to your AWS region
      ECR_REPO_NAME: my-app # Prefix for your ECR repositories

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      # - name: Checkout target branch from another repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: "cloud-devops-assignments/spring-boot-react-example" 
      #     ref: "master"

      - name: Checkout main branch from GitLab repo
        run: |
          git clone --branch master https://gitlab.com/cloud-devops-assignments/spring-boot-react-example gitlab-repo

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build application
        run: |
          cd gitlab-repo
          mvn clean install

      - name: Run Snyk scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --all-projects

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag Docker image
        env:
          BRANCH_NAME: ${{ github.event.inputs.target_branch }}
        run: |
          IMAGE_TAG=$(echo "${BRANCH_NAME}" | tr '/' '-')
          docker build -t $AWS_REGION.amazonaws.com/$ECR_REPO_NAME-$IMAGE_TAG:latest .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker image to ECR
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker push $AWS_REGION.amazonaws.com/$ECR_REPO_NAME-$IMAGE_TAG:latest

      - name: Confirm pushed image
        run: |
          echo "Docker image pushed to ECR repository: $AWS_REGION.amazonaws.com/$ECR_REPO_NAME-${{ env.IMAGE_TAG }}:latest"
